'use client';

import { useState, useEffect } from 'react';
import { ShieldCheckIcon, LockClosedIcon, CheckBadgeIcon } from '../../../../components/Icons';

export default function SecurityPage() {
  const [loading, setLoading] = useState(true);
  const [passwordForm, setPasswordForm] = useState({ currentPassword: '', newPassword: '' });
  const [pwMessage, setPwMessage] = useState<{ type: string; text: string } | null>(null);
  useEffect(() => { setLoading(false); }, []);
  async function handlePasswordChange(e: React.FormEvent) { e.preventDefault(); setPwMessage(null);
    try { const res = await fetch('/api/user', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(passwordForm) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Failed'); setPwMessage({ type: 'success', text: 'Password changed' }); setPasswordForm({ currentPassword: '', newPassword: '' }); } catch (err: any) { setPwMessage({ type: 'error', text: err.message }); }
  }
  if (loading) return null;
  return (<div className="space-y-8"><h1 className="text-2xl font-bold text-white">Security</h1><div className="grid gap-4 sm:grid-cols-3">{[{ label: '2FA Status', value: 'Not Enabled', icon: LockClosedIcon, color: 'text-amber-400', bgColor: 'bg-amber-500/10' },{ label: 'Password Strength', value: 'Strong', icon: ShieldCheckIcon, color: 'text-emerald-400', bgColor: 'bg-emerald-500/10' },{ label: 'Last Login', value: 'Today', icon: CheckBadgeIcon, color: 'text-crestline-400', bgColor: 'bg-crestline-500/10' }].map(item => (<div key={item.label} className="rounded-2xl border border-white/5 bg-slate-900/50 p-6"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.bgColor}`}><item.icon className={`h-5 w-5 ${item.color}`} /></div><p className="mt-3 text-sm text-slate-400">{item.label}</p><p className={`mt-1 text-lg font-semibold ${item.color}`}>{item.value}</p></div>))}</div><div className="max-w-lg rounded-2xl border border-white/5 bg-slate-900/50 p-6"><h2 className="text-lg font-semibold text-white mb-6">Change Password</h2>{pwMessage && <div className={`mb-4 rounded-lg px-4 py-3 text-sm ${pwMessage.type === 'success' ? 'border border-emerald-500/20 bg-emerald-500/5 text-emerald-400' : 'border border-red-500/20 bg-red-500/5 text-red-400'}`}>{pwMessage.text}</div>}<form onSubmit={handlePasswordChange} className="space-y-4"><div><label className="block text-sm font-medium text-slate-300">Current Password</label><input type="password" required value={passwordForm.currentPassword} onChange={e => setPasswordForm(p => ({ ...p, currentPassword: e.target.value }))} className="mt-1.5 block w-full rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white focus:border-crestline-500 focus:outline-none" /></div><div><label className="block text-sm font-medium text-slate-300">New Password</label><input type="password" required minLength={8} value={passwordForm.newPassword} onChange={e => setPasswordForm(p => ({ ...p, newPassword: e.target.value }))} className="mt-1.5 block w-full rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white focus:border-crestline-500 focus:outline-none" /></div><button type="submit" className="rounded-xl bg-crestline-600 px-6 py-2.5 text-sm font-semibold text-white hover:bg-crestline-500 transition-all">Update Password</button></form></div></div>);
}
