'use client';

import { useState, useEffect } from 'react';
import { ArrowTrendingUpIcon } from '../../../../components/Icons';

interface Account { id: string; accountNumber: string; accountType: string; balance: number; }

export default function TransferPage() {
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [fromAccountId, setFromAccountId] = useState('');
  const [toAccountNumber, setToAccountNumber] = useState('');
  const [amount, setAmount] = useState('');
  const [description, setDescription] = useState('');
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [loading, setLoading] = useState(false);
  const [pageLoading, setPageLoading] = useState(true);
  useEffect(() => { fetch('/api/accounts').then(r => r.json()).then(d => { setAccounts(d.accounts || []); if (d.accounts?.length > 0) setFromAccountId(d.accounts[0].id); setPageLoading(false); }); }, []);
  async function handleSubmit(e: React.FormEvent) { e.preventDefault(); setMessage(null); setLoading(true); try { const res = await fetch('/api/transactions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fromAccountId, toAccountNumber, amount: parseFloat(amount), description }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Transfer failed'); setMessage({ type: 'success', text: 'Transfer completed!' }); setAmount(''); setDescription(''); setToAccountNumber(''); } catch (err: any) { setMessage({ type: 'error', text: err.message }); } finally { setLoading(false); } }
  if (pageLoading) return <div className="animate-pulse"><div className="h-8 w-40 rounded bg-slate-800" /></div>;
  return (<div className="space-y-8"><h1 className="text-2xl font-bold text-white">Transfer Money</h1><div className="max-w-lg rounded-2xl border border-white/5 bg-slate-900/50 p-8">{message && <div className={`mb-6 rounded-lg px-4 py-3 text-sm ${message.type === 'success' ? 'border border-emerald-500/20 bg-emerald-500/5 text-emerald-400' : 'border border-red-500/20 bg-red-500/5 text-red-400'}`}>{message.text}</div>}<form onSubmit={handleSubmit} className="space-y-5"><div><label className="block text-sm font-medium text-slate-300">From Account</label><select value={fromAccountId} onChange={e => setFromAccountId(e.target.value)} className="mt-1.5 block w-full rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white focus:border-crestline-500 focus:outline-none">{accounts.map(acc => (<option key={acc.id} value={acc.id}>{acc.accountType.toUpperCase()} — {acc.accountNumber} (${acc.balance.toLocaleString()})</option>))}</select></div><div><label className="block text-sm font-medium text-slate-300">To Account Number</label><input type="text" required value={toAccountNumber} onChange={e => setToAccountNumber(e.target.value)} placeholder="Enter 10-digit account number" className="mt-1.5 block w-full rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white placeholder-slate-500 focus:border-crestline-500 focus:outline-none" /></div><div><label className="block text-sm font-medium text-slate-300">Amount</label><div className="relative mt-1.5"><span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">$</span><input type="number" required min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} className="block w-full rounded-lg border border-white/10 bg-slate-800/50 pl-8 pr-4 py-2.5 text-white focus:border-crestline-500 focus:outline-none" /></div></div><div><label className="block text-sm font-medium text-slate-300">Description (optional)</label><input type="text" value={description} onChange={e => setDescription(e.target.value)} className="mt-1.5 block w-full rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white placeholder-slate-500 focus:border-crestline-500 focus:outline-none" /></div><button type="submit" disabled={loading} className="w-full rounded-xl bg-crestline-600 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-crestline-500/25 hover:bg-crestline-500 disabled:opacity-50">{loading ? 'Processing...' : 'Send Transfer'}</button></form></div></div>);
}
