'use client';

import { useState, useEffect } from 'react';

interface Transaction { id: string; type: string; amount: number; description: string; reference: string; status: string; createdAt: string; fromAccount?: { accountNumber: string; user?: { email: string; firstName: string; lastName: string } }; toAccount?: { accountNumber: string; user?: { email: string; firstName: string; lastName: string } }; }

interface Account { id: string; accountNumber: string; accountType: string; balance: number; user: { email: string; firstName: string; lastName: string } }

export default function AdminTransactionsPage() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [loading, setLoading] = useState(true);
  const [adjustMode, setAdjustMode] = useState(false);
  const [adjustForm, setAdjustForm] = useState({ accountId: '', action: 'credit', amount: '', description: '' });
  const [adjustMsg, setAdjustMsg] = useState<{ type: string; text: string } | null>(null);

  useEffect(() => { Promise.all([fetch('/api/admin/transactions').then(r => r.json()), fetch('/api/accounts').then(r => r.json())]).then(([txn, acc]) => { setTransactions(txn.transactions || []); setAccounts(acc.accounts || []); setLoading(false); }); }, []);

  async function handleAdjust(e: React.FormEvent) { e.preventDefault(); setAdjustMsg(null);
    try { const res = await fetch('/api/admin/transactions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...adjustForm, amount: parseFloat(adjustForm.amount) }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Failed'); setAdjustMsg({ type: 'success', text: 'Adjustment completed' }); setAdjustForm({ accountId: '', action: 'credit', amount: '', description: '' }); const txnRes = await fetch('/api/admin/transactions'); const txnData = await txnRes.json(); setTransactions(txnData.transactions || []); } catch (err: any) { setAdjustMsg({ type: 'error', text: err.message }); }
  }

  if (loading) return <div className="animate-pulse space-y-4"><div className="h-8 w-40 rounded bg-slate-800" /><div className="h-96 rounded-2xl bg-slate-900/50" /></div>;

  return (<div className="space-y-6"><div className="flex items-center justify-between"><h1 className="text-2xl font-bold text-white">Transaction Ledger</h1><button onClick={() => setAdjustMode(!adjustMode)} className={`text-sm px-4 py-2 rounded-lg transition-all ${adjustMode ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20' : 'border border-white/10 text-slate-400 hover:text-white'}`}>{adjustMode ? 'Cancel' : 'Manual Adjustment'}</button></div>
    {adjustMode && (<div className="rounded-2xl border border-amber-500/20 bg-slate-900/50 p-6"><h2 className="text-lg font-semibold text-white mb-4">Manual Account Adjustment</h2>{adjustMsg && <div className={`mb-4 rounded-lg px-4 py-3 text-sm ${adjustMsg.type === 'success' ? 'border border-emerald-500/20 bg-emerald-500/5 text-emerald-400' : 'border border-red-500/20 bg-red-500/5 text-red-400'}`}>{adjustMsg.text}</div>}<form onSubmit={handleAdjust} className="grid gap-4 sm:grid-cols-2"><select value={adjustForm.accountId} onChange={e => setAdjustForm(f => ({ ...f, accountId: e.target.value }))} className="rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white text-sm focus:border-amber-500 focus:outline-none" required><option value="">Select account...</option>{accounts.map(acc => (<option key={acc.id} value={acc.id}>{acc.accountNumber} — {acc.user?.firstName} {acc.user?.lastName} (${acc.balance})</option>))}</select><select value={adjustForm.action} onChange={e => setAdjustForm(f => ({ ...f, action: e.target.value }))} className="rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white text-sm focus:border-amber-500 focus:outline-none"><option value="credit">Credit (+)</option><option value="debit">Debit (−)</option></select><input type="number" required min="0.01" step="0.01" value={adjustForm.amount} onChange={e => setAdjustForm(f => ({ ...f, amount: e.target.value }))} placeholder="Amount" className="rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white text-sm focus:border-amber-500 focus:outline-none" /><input type="text" value={adjustForm.description} onChange={e => setAdjustForm(f => ({ ...f, description: e.target.value }))} placeholder="Reason" className="rounded-lg border border-white/10 bg-slate-800/50 px-4 py-2.5 text-white text-sm focus:border-amber-500 focus:outline-none" /><button type="submit" className="sm:col-span-2 rounded-xl bg-amber-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-amber-500 transition-all">Submit Adjustment</button></form></div>)}
    <div className="rounded-2xl border border-white/5 bg-slate-900/50 overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-white/5"><th className="text-left text-xs text-slate-500 font-medium px-6 py-4">Reference</th><th className="text-left text-xs text-slate-500 font-medium px-6 py-4">Type</th><th className="text-left text-xs text-slate-500 font-medium px-6 py-4">From</th><th className="text-left text-xs text-slate-500 font-medium px-6 py-4">To</th><th className="text-right text-xs text-slate-500 font-medium px-6 py-4">Amount</th><th className="text-left text-xs text-slate-500 font-medium px-6 py-4">Date</th></tr></thead><tbody>{transactions.map(txn => (<tr key={txn.id} className="border-b border-white/5 hover:bg-white/[0.02]"><td className="px-6 py-4 text-xs text-slate-400 font-mono">{txn.reference.slice(-12)}</td><td className="px-6 py-4"><span className={`text-xs px-2 py-0.5 rounded-full ${txn.type === 'admin_credit' || txn.type === 'admin_debit' ? 'bg-amber-500/10 text-amber-400' : txn.type === 'deposit' ? 'bg-emerald-500/10 text-emerald-400' : 'bg-slate-800 text-slate-400'}`}>{txn.type}</span></td><td className="px-6 py-4 text-xs text-slate-400">{txn.fromAccount ? txn.fromAccount.accountNumber : '—'}</td><td className="px-6 py-4 text-xs text-slate-400">{txn.toAccount ? txn.toAccount.accountNumber : '—'}</td><td className={`px-6 py-4 text-xs font-semibold text-right ${txn.type === 'admin_debit' || txn.type === 'withdrawal' ? 'text-red-400' : 'text-emerald-400'}`}>{txn.type === 'admin_debit' || txn.type === 'withdrawal' ? '-' : '+'}${txn.amount.toLocaleString()}</td><td className="px-6 py-4 text-xs text-slate-500">{new Date(txn.createdAt).toLocaleDateString()}</td></tr>))}</tbody></table></div></div>
  </div>);
}
